sudo: required

services:
  - docker

before_install:
  - docker build -t mukeshsopra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mukeshsopra/react-test npm test

after_success:
  - docker build -t mukeshsopra/multi-client ./client
  - docker build -t mukeshsopra/multi-nginx ./nginx
  - docker build -t mukeshsopra/multi-server ./server
  - docker build -t mukeshsopra/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push to docker hub
  - docker push mukeshsopra/multi-client
  - docker push mukeshsopra/multi-nginx
  - docker push mukeshsopra/multi-server
  - docker push mukeshsopra/multi-worker